### PR TITLE
Update SidePanel, Footer and README

### PR DESCRIPTION
**Pull request by pan-grayza**

### CODE REVIEW

**Comment by pan-grayza** [comment]
I realized only now that my local prettier did a lot of stuff. I hope it's not a big deal. I think, we need to add `prettier` config file into repo, to avoid this behavior on other machines

**Comment by pan-grayza** [comment]
Ready to be merged

**Review by addmmyyyy — APPROVED** [review]
Good stuff!
In future, for changes to the aesthetic of the website, throw a screenshot of what your changes look like into the PR description.
Looks good on my machine so I'm approving it

**Comment by Daxorinator** [comment]
Feel free to add the prettier config with some reasonable rules and run it on the repo - just try to avoid updating the entire repo at once, maybe go file by file refactoring stuff as you go. Good opportunity to get some experience with the code that doesn't change very often.

**Pull request merged**
